// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eAJtAG2d3hf13STeHBO1VvJDHcOLbkY',
    appId: '1:908566274960:web:c3a56d0cb34a9207e10915',
    messagingSenderId: '908566274960',
    projectId: 'graduation-project-31ccf',
    authDomain: 'graduation-project-31ccf.firebaseapp.com',
    storageBucket: 'graduation-project-31ccf.firebasestorage.app',
    measurementId: 'G-FVT4Z4N3FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaEU9NqAEYGPFp3C9LWZ5QRqBdY2DDisk',
    appId: '1:908566274960:android:3c3ef9a82dac5d78e10915',
    messagingSenderId: '908566274960',
    projectId: 'graduation-project-31ccf',
    storageBucket: 'graduation-project-31ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KjssTwljRjgY0js5s-ck4ezpczN4c0A',
    appId: '1:908566274960:ios:263010249c401a2ce10915',
    messagingSenderId: '908566274960',
    projectId: 'graduation-project-31ccf',
    storageBucket: 'graduation-project-31ccf.firebasestorage.app',
    androidClientId: '908566274960-10kjqk68nc7smtigqjvabe2hpi0s13l6.apps.googleusercontent.com',
    iosClientId: '908566274960-lvmk4s1cquaja8mjehpm3u4f25b2gnjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gg1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3KjssTwljRjgY0js5s-ck4ezpczN4c0A',
    appId: '1:908566274960:ios:263010249c401a2ce10915',
    messagingSenderId: '908566274960',
    projectId: 'graduation-project-31ccf',
    storageBucket: 'graduation-project-31ccf.firebasestorage.app',
    androidClientId: '908566274960-10kjqk68nc7smtigqjvabe2hpi0s13l6.apps.googleusercontent.com',
    iosClientId: '908566274960-lvmk4s1cquaja8mjehpm3u4f25b2gnjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gg1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3eAJtAG2d3hf13STeHBO1VvJDHcOLbkY',
    appId: '1:908566274960:web:1a6b5c5dfb778c52e10915',
    messagingSenderId: '908566274960',
    projectId: 'graduation-project-31ccf',
    authDomain: 'graduation-project-31ccf.firebaseapp.com',
    storageBucket: 'graduation-project-31ccf.firebasestorage.app',
    measurementId: 'G-W012BBTEE3',
  );
}
